/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.PharmacistRole;

import UI.DoctorRole.*;
import Model.EcoSystem;
import Model.Enterprise.Enterprise;
import Model.Network.Network;
import Model.Organization.DoctorOrg;
import Model.Organization.HealthOrg;
import Model.Organization.Organisation;
import Model.Organization.PharmacyOrg;
import Model.Organization.TransportOrg;
import Model.UserAccount.UserAccount;
import Model.WorkQueue.TutorVolunteerWorkReq;
import Model.WorkQueue.HospitalDoctorWorkReq;
import Model.WorkQueue.HospitalPharmacyWorkReq;
import Model.WorkQueue.LaboratoryTestWorkReq;
import Model.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author DELL
 */
public class HomePagePanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private PharmacyOrg org;
    private Enterprise ent;
    private UserAccount ua;
    private Network net;
    /**
     * Creates new form HomePagePanel
     */
    public HomePagePanel(JPanel userProcessContainer, UserAccount acc, PharmacyOrg org,Network net, Enterprise ent) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.org = (PharmacyOrg)org;
        this.ent = ent;
        this.ua = acc;
        this.net=net;
        autoPopAssignedReq();
    }
    
    public void autoPopAssignedReq() {
        DefaultTableModel mdl = (DefaultTableModel)JM_tblAssignReq.getModel();
        mdl.setRowCount(0);   
        
        for (Iterator<WorkRequest> wr = ua.getWorkQueue().getWrList().iterator(); wr.hasNext();) {
             WorkRequest workRequest = wr.next();
           if(workRequest instanceof HospitalPharmacyWorkReq){
                HospitalPharmacyWorkReq req = (HospitalPharmacyWorkReq)workRequest;
                Object[] row = new Object[6];
                row[0] = req;
                row[1]=req.getNgo();
                row[3]=req.getMedList();
                row[2]=req.getSender();
                row[4] = req.getReqDate();
                row[5]=req.getStatus();
                mdl.addRow(row);
           }
           
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JM_btnRefresh = new javax.swing.JButton();
        JM_jScrollPane1 = new javax.swing.JScrollPane();
        JM_tblAssignReq = new javax.swing.JTable();
        JM_btnViewMedList = new javax.swing.JButton();
        JM_btnProcess = new javax.swing.JButton();
        JM_jScrollPane3 = new javax.swing.JScrollPane();
        JM_txtMessage = new javax.swing.JTextArea();
        JM_btnBacks = new javax.swing.JButton();
        JM_jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        JM_btnRefresh.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        JM_btnRefresh.setForeground(new java.awt.Color(0, 153, 153));
        JM_btnRefresh.setText("Refresh");
        JM_btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_btnRefreshActionPerformed(evt);
            }
        });

        JM_jScrollPane1.setForeground(new java.awt.Color(102, 0, 102));

        JM_tblAssignReq.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        JM_tblAssignReq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NGO", "Sender", "Medicine List", "Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JM_tblAssignReq.setPreferredSize(new java.awt.Dimension(375, 64));
        JM_jScrollPane1.setViewportView(JM_tblAssignReq);

        JM_btnViewMedList.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        JM_btnViewMedList.setForeground(new java.awt.Color(0, 153, 153));
        JM_btnViewMedList.setText("View Medicine List");
        JM_btnViewMedList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_btnViewMedListActionPerformed(evt);
            }
        });

        JM_btnProcess.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        JM_btnProcess.setForeground(new java.awt.Color(0, 153, 153));
        JM_btnProcess.setText("Process");
        JM_btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_btnProcessActionPerformed(evt);
            }
        });

        JM_jScrollPane3.setForeground(new java.awt.Color(102, 0, 102));

        JM_txtMessage.setColumns(20);
        JM_txtMessage.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        JM_txtMessage.setRows(5);
        JM_jScrollPane3.setViewportView(JM_txtMessage);

        JM_btnBacks.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        JM_btnBacks.setForeground(new java.awt.Color(0, 153, 153));
        JM_btnBacks.setText("<<<Back");
        JM_btnBacks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_btnBacksActionPerformed(evt);
            }
        });

        JM_jLabel11.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        JM_jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        JM_jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JM_jLabel11.setText("HomePage");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JM_btnRefresh)
                .addGap(107, 107, 107))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JM_jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(JM_btnProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JM_btnViewMedList))
                                .addComponent(JM_jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(JM_btnBacks)))
                .addContainerGap(206, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JM_jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(JM_jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JM_btnBacks)
                .addGap(20, 20, 20)
                .addComponent(JM_btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JM_jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JM_btnViewMedList, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JM_btnProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(JM_jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JM_btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_btnRefreshActionPerformed
        autoPopAssignedReq();
        JM_txtMessage.setText("");   
    }//GEN-LAST:event_JM_btnRefreshActionPerformed

    private void JM_btnViewMedListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_btnViewMedListActionPerformed
        // TODO add your handling code here:

        int selectedRow = JM_tblAssignReq.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Make row selection");
            return;
        }
        HospitalPharmacyWorkReq req = (HospitalPharmacyWorkReq)JM_tblAssignReq.getValueAt(selectedRow, 0);
        JM_txtMessage.setText(req.getMedList()+" ");
        JM_txtMessage.setEditable(false);
    }//GEN-LAST:event_JM_btnViewMedListActionPerformed

    private void JM_btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_btnProcessActionPerformed

        int selectedRow = JM_tblAssignReq.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "");
            return;
        }

        HospitalPharmacyWorkReq req = (HospitalPharmacyWorkReq)JM_tblAssignReq.getValueAt(selectedRow, 0);
        if(req.getStatus().equalsIgnoreCase("Accepted")){
            JOptionPane.showMessageDialog(null, "Successfully processed and accepted request");
            return;
        }
        req.setStatus("Processing");

        ProcessMedReq processMedReq = new ProcessMedReq(userProcessContainer,ent, ua, req);
        userProcessContainer.add("processMedReq", processMedReq);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_JM_btnProcessActionPerformed

    private void JM_btnBacksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_btnBacksActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_JM_btnBacksActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JM_btnBacks;
    private javax.swing.JButton JM_btnProcess;
    private javax.swing.JButton JM_btnRefresh;
    private javax.swing.JButton JM_btnViewMedList;
    private javax.swing.JLabel JM_jLabel11;
    private javax.swing.JScrollPane JM_jScrollPane1;
    private javax.swing.JScrollPane JM_jScrollPane3;
    private javax.swing.JTable JM_tblAssignReq;
    private javax.swing.JTextArea JM_txtMessage;
    // End of variables declaration//GEN-END:variables
}
