/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.PharmacistRole;

import UI.DoctorRole.*;
import Model.EcoSystem;
import Model.Enterprise.Enterprise;
import Model.Network.Network;
import Model.Organization.PharmacyOrg;
import Model.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author Mrinalini
 */
public class PharmacistPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private PharmacyOrg org;
    private Enterprise ent;
    private UserAccount ua;
    private Network net;
    /**
     * Creates new form PharmacistPanel
     */
    public PharmacistPanel(JPanel userProcessContainer, UserAccount acc, PharmacyOrg org,Network net, Enterprise ent) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.org = (PharmacyOrg)org;
        this.ent = ent;
        this.ua = acc;
        this.net=net;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JM_btnNewReq = new javax.swing.JButton();
        JM_btnHomePage = new javax.swing.JButton();
        JM_btnDelivery = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        JM_btnNewReq.setForeground(new java.awt.Color(0, 153, 153));
        JM_btnNewReq.setText("New Requests");
        JM_btnNewReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_btnNewReqActionPerformed(evt);
            }
        });

        JM_btnHomePage.setForeground(new java.awt.Color(0, 153, 153));
        JM_btnHomePage.setText("HomePage");
        JM_btnHomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_btnHomePageActionPerformed(evt);
            }
        });

        JM_btnDelivery.setForeground(new java.awt.Color(0, 153, 153));
        JM_btnDelivery.setText("Delivery");
        JM_btnDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_btnDeliveryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JM_btnHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JM_btnNewReq)
                    .addComponent(JM_btnDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(904, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(JM_btnHomePage)
                .addGap(78, 78, 78)
                .addComponent(JM_btnNewReq)
                .addGap(91, 91, 91)
                .addComponent(JM_btnDelivery)
                .addContainerGap(451, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JM_btnNewReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_btnNewReqActionPerformed
        // TODO add your handling code here:
        NewRequestPanel newRequestPanel = new NewRequestPanel(userProcessContainer, ua, org, net, ent);
        userProcessContainer.add("newRequestPanel", newRequestPanel);
        newRequestPanel.autoPopMedList();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_JM_btnNewReqActionPerformed

    private void JM_btnHomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_btnHomePageActionPerformed
        // TODO add your handling code here:
        HomePagePanel homePagePanel = new HomePagePanel(userProcessContainer, ua, org, net, ent);
        userProcessContainer.add("homePagePanel", homePagePanel);
        homePagePanel.autoPopAssignedReq();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_JM_btnHomePageActionPerformed

    private void JM_btnDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_btnDeliveryActionPerformed
        // TODO add your handling code here:
        DeliveryPanel deliveryPanel = new DeliveryPanel(userProcessContainer, ua, org, net, ent);
        userProcessContainer.add("deliveryPanel", deliveryPanel);
        deliveryPanel.autoPopDelivery();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_JM_btnDeliveryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JM_btnDelivery;
    private javax.swing.JButton JM_btnHomePage;
    private javax.swing.JButton JM_btnNewReq;
    // End of variables declaration//GEN-END:variables
}
