/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.PharmacistRole;
import Business.Enterprise.Enterprise;
import Business.Medicare;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HospitalDoctorWorkReq;
import Business.WorkQueue.HospitalPharmacyWorkReq;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import UI.HealthRole.MedJPanel;
/**
 *
 * @author Mrinalini
 */
public class ProcessMedReq extends javax.swing.JPanel {

    /**
     * Creates new form ProcessMedReq
     */
    private JPanel userProcessContainer;
    private Enterprise ent;
    private HospitalPharmacyWorkReq req;
    private UserAccount ua;
    
    public ProcessMedReq(JPanel userProcessContainer, Enterprise ent, UserAccount acc, HospitalPharmacyWorkReq req) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ent = ent;
        this.ua = acc;
        this.req = req;
        populateTable();
        JM_txtAddress.setText(req.getAddress());

        if(req.getPrescription()==null){
            JM_imgPresciption.setText("No Image Uploaded");
            JM_imgPresciption.setHorizontalAlignment(SwingConstants.CENTER);
        }
        else{
            JM_imgPresciption.setText("");
            JM_imgPresciption.setIcon(imgResize(req.getPrescription()));
        }
        if(req.getStatus().equalsIgnoreCase("Processing") || req.getStatus().equalsIgnoreCase("Declined")){
            JM_txtMessage.setText(req.getMessage());
        }
    }
    
    private void populateTable() {
       List<Medicare> medList = req.getMedList();
        DefaultTableModel defaultTableModel = (DefaultTableModel) JM_tblMedRequestedList.getModel();
        defaultTableModel.setRowCount(0);
        for(Medicare med:medList){
            Object[] row =new Object[2];
            row[0] = med;
            row[1] = med.getMed_quantity();
            defaultTableModel.addRow(row);
        }
    }
    
    private ImageIcon imgResize(String imgPath){
        ImageIcon myImg = new ImageIcon(imgPath);
        Image img = myImg.getImage();
        Image newImg = img.getScaledInstance(272,306, Image.SCALE_SMOOTH);
        ImageIcon finalImg = new ImageIcon(newImg);
        return finalImg;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JM_btnBAck = new javax.swing.JButton();
        JM_jLabel10 = new javax.swing.JLabel();
        JM_btnSubmit = new javax.swing.JButton();
        JM_imgPresciption = new javax.swing.JLabel();
        JM_jScrollPane3 = new javax.swing.JScrollPane();
        JM_txtAddress = new javax.swing.JTextArea();
        JM_jLabel2 = new javax.swing.JLabel();
        JM_jLabel3 = new javax.swing.JLabel();
        JM_jScrollPane2 = new javax.swing.JScrollPane();
        JM_tblMedRequestedList = new javax.swing.JTable();
        JM_jScrollPane1 = new javax.swing.JScrollPane();
        JM_txtMessage = new javax.swing.JTextArea();
        JM_jLabel1 = new javax.swing.JLabel();
        JM_btnAccept = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        JM_btnBAck.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        JM_btnBAck.setForeground(new java.awt.Color(0, 153, 153));
        JM_btnBAck.setText("<< Back");
        JM_btnBAck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_btnBAckActionPerformed(evt);
            }
        });

        JM_jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        JM_jLabel10.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        JM_jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        JM_jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JM_jLabel10.setText("Process Medicine Request");

        JM_btnSubmit.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        JM_btnSubmit.setForeground(new java.awt.Color(0, 153, 153));
        JM_btnSubmit.setText("SUBMIT");
        JM_btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_btnSubmitActionPerformed(evt);
            }
        });

        JM_imgPresciption.setBackground(new java.awt.Color(255, 255, 255));
        JM_imgPresciption.setForeground(new java.awt.Color(255, 255, 255));
        JM_imgPresciption.setText("Insert Image");
        JM_imgPresciption.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JM_jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        JM_jScrollPane3.setForeground(new java.awt.Color(102, 0, 102));

        JM_txtAddress.setEditable(false);
        JM_txtAddress.setColumns(20);
        JM_txtAddress.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        JM_txtAddress.setRows(5);
        JM_jScrollPane3.setViewportView(JM_txtAddress);

        JM_jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        JM_jLabel2.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        JM_jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        JM_jLabel2.setText("Message:");

        JM_jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        JM_jLabel3.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        JM_jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        JM_jLabel3.setText("Prescription:");

        JM_jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        JM_jScrollPane2.setForeground(new java.awt.Color(102, 0, 102));

        JM_tblMedRequestedList.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        JM_tblMedRequestedList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JM_jScrollPane2.setViewportView(JM_tblMedRequestedList);

        JM_jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        JM_jScrollPane1.setForeground(new java.awt.Color(102, 0, 102));

        JM_txtMessage.setColumns(20);
        JM_txtMessage.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        JM_txtMessage.setRows(5);
        JM_jScrollPane1.setViewportView(JM_txtMessage);

        JM_jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        JM_jLabel1.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        JM_jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        JM_jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        JM_jLabel1.setText("Address:");

        JM_btnAccept.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        JM_btnAccept.setForeground(new java.awt.Color(0, 153, 153));
        JM_btnAccept.setText("ACCEPT");
        JM_btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_btnAcceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JM_jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JM_btnBAck))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(345, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JM_jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JM_jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(JM_jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JM_jLabel3)
                                    .addComponent(JM_imgPresciption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JM_jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JM_jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(JM_btnAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JM_btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(237, 237, 237)))))
                .addContainerGap(345, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JM_btnBAck)
                .addGap(15, 15, 15)
                .addComponent(JM_jLabel10)
                .addGap(35, 35, 35)
                .addComponent(JM_jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JM_jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(JM_imgPresciption, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JM_jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JM_jLabel1)
                    .addComponent(JM_jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JM_jLabel2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JM_btnAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JM_btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JM_btnBAckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_btnBAckActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        HomePagePanel homePagePanel = (HomePagePanel) component;
        homePagePanel.autoPopAssignedReq();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_JM_btnBAckActionPerformed

    private void JM_btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_btnSubmitActionPerformed

        String message = JM_txtMessage.getText();
        if(message.equals("") || message==null){
            JOptionPane.showMessageDialog(null, "Update Message");
            return;
        }
        req.setMessage(message);
        req.setStatus("Declined");
        req.setResDate(new Date());
        JOptionPane.showConfirmDialog(null, "Response Submission?");
    }//GEN-LAST:event_JM_btnSubmitActionPerformed

    private void JM_btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_btnAcceptActionPerformed

        req.setStatus("Accepted");
        req.setResDate(new Date());
        req.setMessage("");
        JOptionPane.showConfirmDialog(null, "Do you want Request Acceptance?");
    }//GEN-LAST:event_JM_btnAcceptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JM_btnAccept;
    private javax.swing.JButton JM_btnBAck;
    private javax.swing.JButton JM_btnSubmit;
    private javax.swing.JLabel JM_imgPresciption;
    private javax.swing.JLabel JM_jLabel1;
    private javax.swing.JLabel JM_jLabel10;
    private javax.swing.JLabel JM_jLabel2;
    private javax.swing.JLabel JM_jLabel3;
    private javax.swing.JScrollPane JM_jScrollPane1;
    private javax.swing.JScrollPane JM_jScrollPane2;
    private javax.swing.JScrollPane JM_jScrollPane3;
    private javax.swing.JTable JM_tblMedRequestedList;
    private javax.swing.JTextArea JM_txtAddress;
    private javax.swing.JTextArea JM_txtMessage;
    // End of variables declaration//GEN-END:variables
}
