/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.StorageRole;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrg;
import Business.Organization.TutorOrg;
import Business.Organization.StorageOrg;
import Business.Organization.Organisation;
import Business.Organization.TransportOrg;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.TutorVolunteerWorkReq;
import Business.WorkQueue.VolunteerStorageWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mrinalini
 */
public class NewDonations extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private StorageOrg org;
    private Enterprise ent;
    private UserAccount ua;
    private Network net;
    /**
     * Creates new form NewDonations
     */
    public NewDonations(JPanel userProcessContainer, UserAccount acc, StorageOrg org, Enterprise ent, Network net) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.org = (StorageOrg)org;
        this.ent = ent;
        this.ua = acc;
        this.net = net;

        autoPopNewDonation();
    }

    public void autoPopNewDonation(){
        DefaultTableModel mdl = (DefaultTableModel)tblNewDonations.getModel();
        
        mdl.setRowCount(0);
        
        for (Iterator<WorkRequest> wr = org.getWorkQueue().getWrList().iterator(); wr.hasNext();) {
            VolunteerStorageWorkRequest req = (VolunteerStorageWorkRequest) wr.next();
                if(req.getStatus().equalsIgnoreCase("Sent")){
                    Object[] row = new Object[4];
                    row[0]=req;
                    row[1] = req.getSender();
                    row[2]=req.getSenderNumber();
                    int sum=0;
                    for(Integer in: req.getQuantity())
                    {
                        sum=sum+in;
                    }
                    row[3]=sum;
                    mdl.addRow(row);
                }
                
        }
       
    }
    
    public void autoPopViewDetails(ArrayList<String> cat, ArrayList<Integer> quantity, ArrayList<String> desc)
    {
        DefaultTableModel mdl = (DefaultTableModel) tbViewlDetails.getModel();
        mdl.setRowCount(0);
        int length= cat.size();
        for(int i=0;i<length;i++)
        {
            Object[] row = new Object[3];
            row[0] = cat.get(i);
            row[1] = quantity.get(i);
            row[2] = desc.get(i);
            mdl.addRow(row);
        }
    }
    
    private boolean checkPhoneNo(String phNo) {
        Pattern pattern = Pattern.compile("^[0-9]{10}$");
        Matcher matcher = pattern.matcher(phNo);
        return matcher.matches();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel25 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblNewDonations = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbViewlDetails = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtDelAddr = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        txtphNo = new javax.swing.JTextField();
        btnOrder = new javax.swing.JButton();

        jLabel25.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 0, 102));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Storage Work Area");

        jLabel2.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Donations");

        jLabel1.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Details");

        tblNewDonations.setForeground(new java.awt.Color(102, 0, 102));
        tblNewDonations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Donation ID", "Sender", "Number", "Total Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNewDonations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNewDonationsMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblNewDonations);

        tbViewlDetails.setForeground(new java.awt.Color(102, 0, 102));
        tbViewlDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category", "Quantity", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tbViewlDetails);

        jLabel24.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Delivery Address:");

        txtDelAddr.setColumns(20);
        txtDelAddr.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        txtDelAddr.setRows(5);
        jScrollPane7.setViewportView(txtDelAddr);

        jLabel11.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        jLabel11.setText("Contact Number:");

        txtphNo.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N

        btnOrder.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnOrder.setText("Order Now");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(338, 338, 338))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jLabel11)
                        .addGap(64, 64, 64)
                        .addComponent(txtphNo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(461, 461, 461))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel25)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(31, 31, 31)
                        .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtphNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(236, 236, 236))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblNewDonationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNewDonationsMouseClicked
        int selectedRow = tblNewDonations.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showConfirmDialog(null, "Make row selection to view desired details.","Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            VolunteerStorageWorkRequest req = (VolunteerStorageWorkRequest)tblNewDonations.getValueAt(selectedRow, 0);

            autoPopViewDetails(req.getCategory(),req.getQuantity(),req.getDescription());
        }
    }//GEN-LAST:event_tblNewDonationsMouseClicked

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblNewDonations.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showConfirmDialog(null, "Opt a row from table to place an order.","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String addr = txtDelAddr.getText();
        if(addr==null || addr.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Address");
            return;
        }
        String phNo = txtphNo.getText();
        if(phNo == null || phNo.equals("")){
            JOptionPane.showMessageDialog(null, "Phone Number cannot be left empty");
            return;
        }
        if(!checkPhoneNo(phNo)){
            JOptionPane.showMessageDialog(null, "Invalid contact no.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        VolunteerStorageWorkRequest req = (VolunteerStorageWorkRequest)tblNewDonations.getValueAt(selectedRow, 0);
        req.setReceiver(ua);
        req.setRecieverAddress(addr);
        req.setRecieverNumber(phNo);
        req.setStatus("Ordered");
        ua.getWorkQueue().getWrList().add(req);
        JOptionPane.showMessageDialog(null, "Order Successfully Placed . \n Your Order Id for the order is "+req.getOrdID());

        autoPopNewDonation();
        
        DefaultTableModel mdl = (DefaultTableModel) tbViewlDetails.getModel();
        mdl.setRowCount(0);
//        DefaultTableModel mdl1 = (DefaultTableModel) tblOrdDetails.getModel();
//        model2.setRowCount(0);

        for(Enterprise ent: net.getEntDir().getEntList())
        {
            if(ent.getEntType().equals(ent.getEntType().Transpotation))
            {
                for (Organisation organisation : ent.getOrgDir().getOrgList())
                {
                    if (organisation instanceof TransportOrg){
                        organisation.getWorkQueue().getWrList().add(req);
                    }
                }
            }
        }

    }//GEN-LAST:event_btnOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable tbViewlDetails;
    private javax.swing.JTable tblNewDonations;
    private javax.swing.JTextArea txtDelAddr;
    private javax.swing.JTextField txtphNo;
    // End of variables declaration//GEN-END:variables
}
