/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.TutorRole;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.TutorVolunteerWorkReq;
import java.awt.CardLayout;
import java.awt.Component;
import java.time.LocalDate;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author krishna
 */
public class ViewVolPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private TutorVolunteerWorkReq req;
    /**
     * Creates new form ViewVolOanel
     */
    public ViewVolPanel(JPanel userProcessContainer, TutorVolunteerWorkReq req) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.req = req;
        autoPopVol();
    }
    
    private void autoPopVol(){
        
        DefaultTableModel mdl = (DefaultTableModel) tblVolList.getModel();
       
        mdl.setRowCount(0);
        for (Iterator<UserAccount> wr = req.getUsersList().iterator(); wr.hasNext();) {
            UserAccount ua = (UserAccount) wr.next();
            Object[] row = new Object[5];
            row[0] = ua;
            row[1] = ua.getEmp().getSex();
            
             LocalDate nowDate = LocalDate.now();
             LocalDate dob = ua.getEmp().getDob();
             int age = ua.getEmp().ageCalculator(dob, nowDate);
             
            row[2] = age;
            row[3] = ua.getEmp().getEmail(); 
            row[4] = ua.getEmp().getPhNo();
            mdl.addRow(row);
        }
        
    }

    private void autoPopBlanks(){
        
            txtName.setText("");
            txtSex.setText("");
            txtAge.setText("");
            txtEmail.setText("");
            txtPhNo.setText("");
            txtAddress.setText("");
            txtCity.setText("");
            txtPincode.setText("");
            txtSkills.setText("");
            txtEducation.setText("");
            txtLanguage.setText("");
            txtEnglish.setText("");
            chbEmail.setSelected(false);
            chbExcel.setSelected(false);
            chbPowerPoint.setSelected(false);
            chbWord.setSelected(false);
            chbWeb.setSelected(false);
        
    }
    
    private void autoPopVolDetails(UserAccount ua){
        
            txtName.setText(ua.getEmp().getName());
            txtSex.setText(ua.getEmp().getSex());
            
             LocalDate nowDate = LocalDate.now();
             LocalDate birthdate = ua.getEmp().getDob();
             int age = ua.getEmp().ageCalculator(birthdate, nowDate);
             txtAge.setText(String.valueOf(age));
            
            txtAge.setText(String.valueOf(age));
            txtEmail.setText(ua.getEmp().getEmail());
            txtPhNo.setText(ua.getEmp().getPhNo());
            txtAddress.setText(ua.getVolunteer().getAddress());
            txtPincode.setText(ua.getVolunteer().getPincode());
            txtSkills.setText(ua.getVolunteer().getSkills());
            txtEnglish.setText(ua.getVolunteer().getEngProficent());
            
            autoPopLanguage(ua);
            autoPopEducation(ua);
            
            if(ua.getVolunteer().getExpertise().contains("MS Word")){
                chbWord.setSelected(true);
            }
            if(ua.getVolunteer().getExpertise().contains("MS Excel")){
                chbExcel.setSelected(true);
            }
            if(ua.getVolunteer().getExpertise().contains("PowerPoint")){
                chbPowerPoint.setSelected(true);
            }
            if(ua.getVolunteer().getExpertise().contains("Web Browsing")){
                chbWeb.setSelected(true);
            }
            if(ua.getVolunteer().getExpertise().contains("Email Checking")){
                chbEmail.setSelected(true);
            }   
    }
    
    private void autoPopLanguage(UserAccount ua){
        
        for(String lang: ua.getVolunteer().getLanguages()){
                 txtLanguage.append(lang + "\n");
            }
    }
    
    private void autoPopEducation(UserAccount ua){
        txtEducation.setText("");
        int cnt = 1;
        for(Map.Entry<String,String> entry : ua.getVolunteer().getEduList().entrySet()){
            txtEducation.append(cnt + ".  " + entry.getKey() + " " + entry.getValue() + "\n");
            cnt++;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtSkills = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        btnDecline = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtSex = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVolList = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        chbPowerPoint = new javax.swing.JCheckBox();
        chbEmail = new javax.swing.JCheckBox();
        chbWeb = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtPincode = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtLanguage = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        txtEnglish = new javax.swing.JTextField();
        txtPhNo = new javax.swing.JTextField();
        chbWord = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        chbExcel = new javax.swing.JCheckBox();
        txtEmail = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEducation = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel9.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Contact Information");

        jLabel20.setFont(new java.awt.Font(".SF NS Mono", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Work Knowledge of:");

        txtName.setEditable(false);
        txtName.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(102, 0, 102));

        jLabel1.setFont(new java.awt.Font(".SF NS Mono", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Name: ");

        txtSkills.setEditable(false);
        txtSkills.setColumns(20);
        txtSkills.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        txtSkills.setRows(5);
        jScrollPane4.setViewportView(txtSkills);

        jLabel8.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Personal Information");

        jLabel10.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Volunteers Details");

        txtAge.setEditable(false);
        txtAge.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        txtAge.setForeground(new java.awt.Color(102, 0, 102));

        btnDecline.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        btnDecline.setForeground(new java.awt.Color(0, 153, 153));
        btnDecline.setText("Decline Request");
        btnDecline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclineActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font(".SF NS Mono", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Age:");

        txtSex.setEditable(false);
        txtSex.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        txtSex.setForeground(new java.awt.Color(102, 0, 102));

        tblVolList.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        tblVolList.setForeground(new java.awt.Color(102, 0, 102));
        tblVolList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Gender", "Age", "Email ID", "Phone No.", "Nationality"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVolList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVolListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVolList);

        jLabel2.setFont(new java.awt.Font(".SF NS Mono", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sex: ");

        jLabel21.setFont(new java.awt.Font(".SF NS Mono", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Skills:");

        chbPowerPoint.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        chbPowerPoint.setForeground(new java.awt.Color(255, 255, 255));
        chbPowerPoint.setText("PowerPoint");

        chbEmail.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        chbEmail.setForeground(new java.awt.Color(255, 255, 255));
        chbEmail.setText("Email Checking");

        chbWeb.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        chbWeb.setForeground(new java.awt.Color(255, 255, 255));
        chbWeb.setText("Web Browsing");

        jLabel17.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Language Proficency & Skills");

        jLabel15.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Pincode:");

        txtPincode.setEditable(false);
        txtPincode.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        txtPincode.setForeground(new java.awt.Color(102, 0, 102));
        txtPincode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPincodeActionPerformed(evt);
            }
        });

        txtCity.setEditable(false);
        txtCity.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        txtCity.setForeground(new java.awt.Color(102, 0, 102));
        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font(".SF NS Mono", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("English: ");

        jLabel14.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("City:");

        jLabel19.setFont(new java.awt.Font(".SF NS Mono", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Other Language:");

        txtAddress.setEditable(false);
        txtAddress.setColumns(20);
        txtAddress.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        txtAddress.setRows(5);
        jScrollPane5.setViewportView(txtAddress);

        txtLanguage.setEditable(false);
        txtLanguage.setColumns(20);
        txtLanguage.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        txtLanguage.setRows(5);
        jScrollPane3.setViewportView(txtLanguage);

        jLabel13.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Address:");

        txtEnglish.setEditable(false);
        txtEnglish.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        txtEnglish.setForeground(new java.awt.Color(102, 0, 102));
        txtEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnglishActionPerformed(evt);
            }
        });

        txtPhNo.setEditable(false);
        txtPhNo.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        txtPhNo.setForeground(new java.awt.Color(102, 0, 102));
        txtPhNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhNoActionPerformed(evt);
            }
        });

        chbWord.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        chbWord.setForeground(new java.awt.Color(255, 255, 255));
        chbWord.setText("MS Word");
        chbWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbWordActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contact Number:");

        jLabel11.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Education");

        jLabel5.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email Id:");

        chbExcel.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        chbExcel.setForeground(new java.awt.Color(255, 255, 255));
        chbExcel.setText("MS Excel");

        txtEmail.setEditable(false);
        txtEmail.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(102, 0, 102));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(102, 0, 102));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtEducation.setEditable(false);
        txtEducation.setColumns(20);
        txtEducation.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        txtEducation.setForeground(new java.awt.Color(102, 0, 102));
        txtEducation.setRows(5);
        jScrollPane2.setViewportView(txtEducation);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(61, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(127, 127, 127)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtAge)
                                                .addComponent(txtSex, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel13))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPhNo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPincode, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel21))
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(chbPowerPoint, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(chbWord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(chbExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(chbEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(chbWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtEnglish, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDecline, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(15, 15, 15)
                .addComponent(jLabel10)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDecline, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(txtEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chbWord)
                            .addComponent(chbEmail)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chbExcel)
                            .addComponent(chbWeb))
                        .addGap(11, 11, 11)
                        .addComponent(chbPowerPoint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtPhNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel15))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPincode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeclineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclineActionPerformed
        int selectedRow = tblVolList.getSelectedRow();
        if(selectedRow>=0){
            int selBtn = JOptionPane.YES_NO_OPTION;
            int selRes = JOptionPane.showConfirmDialog(null, "Do you want to cancel request?","Warning",selBtn);
            
            if(selRes == JOptionPane.YES_OPTION){
                UserAccount vol = (UserAccount)tblVolList.getValueAt(selectedRow, 0);

                vol.getWorkQueue().getWrList().remove(req);
                req.getUsersList().remove(vol);
                
                int vacancy = req.getVacancy();
                req.setVacancy(vacancy + 1);
                if(req.getVacancy()== 0){
                    req.setStatus("Completed");
                }
                else{
                    req.setStatus("Pending");
                }
                autoPopVol();
                autoPopBlanks();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Make row selection");
        }
    }//GEN-LAST:event_btnDeclineActionPerformed

    private void tblVolListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVolListMouseClicked
        int selectedrow= tblVolList.getSelectedRow();
        if (selectedrow>=0)
        {
            UserAccount vol = (UserAccount)tblVolList.getValueAt(selectedrow, 0);
            autoPopVolDetails(vol);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Make row selection","Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_tblVolListMouseClicked

    private void txtPincodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPincodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPincodeActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnglishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnglishActionPerformed

    private void txtPhNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhNoActionPerformed

    private void chbWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbWordActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        TutorPanel tutorPanel = (TutorPanel) component;
        tutorPanel.autoPopReqTbl();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDecline;
    private javax.swing.JCheckBox chbEmail;
    private javax.swing.JCheckBox chbExcel;
    private javax.swing.JCheckBox chbPowerPoint;
    private javax.swing.JCheckBox chbWeb;
    private javax.swing.JCheckBox chbWord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tblVolList;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextArea txtEducation;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEnglish;
    private javax.swing.JTextArea txtLanguage;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhNo;
    private javax.swing.JTextField txtPincode;
    private javax.swing.JTextField txtSex;
    private javax.swing.JTextArea txtSkills;
    // End of variables declaration//GEN-END:variables
}
