/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.AdminRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Enterprise.NGOEnterprise;
import Business.Enterprise.ResturantEnterprise;
import Business.Enterprise.TransportationEnterprise;
import Business.Organization.Organisation;
import Business.Organization.Organisation.Type;
import Business.Organization.OrganisationDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author monalikapradhan
 */

public class ManageOrgJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrgJPanel
     */
    private OrganisationDirectory dir;
    private JPanel userProcessContainer;
    private Enterprise ent;
    
    public ManageOrgJPanel(JPanel userProcessContainer,OrganisationDirectory dir, Enterprise ent) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.dir = dir;
        this.ent = ent;
        autoPopTbl();
        autoPopCB();
    }
    private void autoPopCB(){       
        cborg.removeAllItems();
        if(ent.getEntType().equals(Enterprise.EntType.NGO)){
            for (NGOEnterprise.Type type : NGOEnterprise.Type.values()){
            if (!type.getType().equals(Type.Admin.getOrgType()))
                cborg.addItem(type);
            }
        }else if(ent.getEntType().equals(Enterprise.EntType.Hospital)){
           
            for (HospitalEnterprise.Type type : HospitalEnterprise.Type.values()){
            if (!type.getType().equals(Type.Admin.getOrgType()))
                cborg.addItem(type);
            }
        }else if(ent.getEntType().equals(Enterprise.EntType.Transpotation)){
           
            for (TransportationEnterprise.Type type : TransportationEnterprise.Type.values()){
            if (!type.getType().equals(Type.Admin.getOrgType()))
                cborg.addItem(type);
            }
        } else{
            for(ResturantEnterprise.Type type: ResturantEnterprise.Type.values()){
                cborg.addItem(type);
            }
        }
    }
    
    private void autoPopTbl(){
        DefaultTableModel mdl = (DefaultTableModel) orgtable.getModel();
        mdl.setRowCount(0);
        for (Organisation org : dir.getOrgList()){
            Object[] row = new Object[2];
            row[0] = org.getOrgID();
            row[1] = org.getName();
            mdl.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        orgtable = new javax.swing.JTable();
        btnaddorg = new javax.swing.JButton();
        cborg = new javax.swing.JComboBox();
        lblorgtype = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        lbltitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        orgtable.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        orgtable.setForeground(new java.awt.Color(102, 0, 102));
        orgtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orgtable);

        btnaddorg.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        btnaddorg.setForeground(new java.awt.Color(0, 153, 153));
        btnaddorg.setText("Add Organization");
        btnaddorg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddorgActionPerformed(evt);
            }
        });

        cborg.setFont(new java.awt.Font(".SF NS Mono", 1, 14)); // NOI18N
        cborg.setForeground(new java.awt.Color(0, 153, 153));
        cborg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cborg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cborgActionPerformed(evt);
            }
        });

        lblorgtype.setBackground(new java.awt.Color(255, 255, 255));
        lblorgtype.setFont(new java.awt.Font(".SF NS Mono", 1, 14)); // NOI18N
        lblorgtype.setForeground(new java.awt.Color(255, 255, 255));
        lblorgtype.setText("Organization Type ");

        btnback.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        btnback.setForeground(new java.awt.Color(0, 153, 153));
        btnback.setText("<< Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        lbltitle.setBackground(new java.awt.Color(255, 255, 255));
        lbltitle.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        lbltitle.setForeground(new java.awt.Color(255, 255, 255));
        lbltitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle.setText("MANAGE ORGANIZATION WORKAREA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblorgtype)
                            .addComponent(cborg, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnaddorg)
                            .addComponent(btnback))
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(539, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblorgtype)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cborg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnaddorg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGap(174, 174, 174)
                .addComponent(btnback)
                .addContainerGap(211, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddorgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddorgActionPerformed
    

        if(ent.getEntType().equals(Enterprise.EntType.NGO)){
            NGOEnterprise.Type type = (NGOEnterprise.Type) cborg.getSelectedItem();
                System.out.println("-----"+type+"----"+type.getType()+"-----"+dir.getOrgList());
            for(Organisation org: dir.getOrgList()){
                System.out.println("-------"+org.getName());
                if(org.getName().equals(type.getType())){
                    JOptionPane.showMessageDialog(null, "This organisation already exists.");
                    return;
                }
            }
            System.out.println("0000---------"+dir);
            dir.createNGOOrg(type);

        }else if(ent.getEntType().equals(Enterprise.EntType.Hospital)){
            HospitalEnterprise.Type type = (HospitalEnterprise.Type) cborg.getSelectedItem();
            for(Organisation org: dir.getOrgList()){
                if(org.getName().equals(type.getType())){
                    JOptionPane.showMessageDialog(null, "This organisation already exists.");
                    return;
                }
            }
            dir.createHospOrg(type);
        }else if(ent.getEntType().equals(Enterprise.EntType.Transpotation)){
            TransportationEnterprise.Type type = (TransportationEnterprise.Type) cborg.getSelectedItem();
            for(Organisation org: dir.getOrgList()){
                if(org.getName().equals(type.getType())){
                    JOptionPane.showMessageDialog(null, "This organisation already exists.");
                    return;
                }
            }
            dir.createLTranportationOrg(type);
        }
        else {
            ResturantEnterprise.Type type = (ResturantEnterprise.Type) cborg.getSelectedItem();
            for(Organisation org: dir.getOrgList()){
                if(org.getName().equals(type.getType())){
                    JOptionPane.showMessageDialog(null, "This organisation already exists.");
                    return;
                }
            }
            dir.createRestaurantOrg(type);
        }
        System.out.println("----existed========");
        autoPopTbl();

    }//GEN-LAST:event_btnaddorgActionPerformed

    private void cborgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cborgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cborgActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddorg;
    private javax.swing.JButton btnback;
    private javax.swing.JComboBox cborg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblorgtype;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JTable orgtable;
    // End of variables declaration//GEN-END:variables
}
