/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.AdminRole;

import Model.Employee.Employee;
import Model.Employee.Volunteer;
import Model.Enterprise.Enterprise;
import Model.Organization.Organisation;
import Model.Role.Role;
import static Model.Role.Role.Type.Volunteer;
import Model.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author monalikapradhan
 */
public class ManageUserAccJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageUserAccJPanel
     */
    private JPanel container;
    private Enterprise ent;

    public ManageUserAccJPanel(JPanel usercontainer, Enterprise ent) {
        initComponents();
        this.ent = ent;
        this.container = usercontainer;
        popOrgCB();
        autoPopData();
    }
    public void popOrgCB() {
        JM_orgcb.removeAllItems();
        for (Organisation org : ent.getOrgDir().getOrgList()) {
            JM_orgcb.addItem(org);
        }
    }
    public void populateEmployeeComboBox(Organisation org){
        JM_empcb.removeAllItems();
        for (Employee emp : org.getEmpDir().getEmpList()){
            JM_empcb.addItem(emp);
        }
    }
    private void populateRoleComboBox(Organisation org){
        JM_rolecb.removeAllItems();
        for (Role role : org.getRoleList()){
            JM_rolecb.addItem(role);
        }
    }
    public void autoPopData() {
        DefaultTableModel mdl = (DefaultTableModel) JM_usertable.getModel();
        mdl.setRowCount(0);
        for (Organisation org : ent.getOrgDir().getOrgList()) {
            for (UserAccount ua : org.getUserAccDir().getUserAccList()) {
                Object row[] = new Object[2];
                row[0] = ua;
                row[1] = ua.getRole();
                ((DefaultTableModel) JM_usertable.getModel()).addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JM_btncreate = new javax.swing.JButton();
        JM_lblusername = new javax.swing.JLabel();
        JM_jScrollPane1 = new javax.swing.JScrollPane();
        JM_usertable = new javax.swing.JTable();
        JM_lblpwd = new javax.swing.JLabel();
        JM_lblemp = new javax.swing.JLabel();
        JM_empcb = new javax.swing.JComboBox();
        JM_lblorg = new javax.swing.JLabel();
        JM_orgcb = new javax.swing.JComboBox();
        JM_lblrole = new javax.swing.JLabel();
        JM_rolecb = new javax.swing.JComboBox();
        JM_btnback = new javax.swing.JButton();
        JM_lbltitle = new javax.swing.JLabel();
        JM_txtusername = new javax.swing.JTextField();
        JM_txtpwd = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(0, 153, 153));
        setForeground(new java.awt.Color(102, 0, 102));

        JM_btncreate.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        JM_btncreate.setForeground(new java.awt.Color(0, 153, 153));
        JM_btncreate.setText("Create User");
        JM_btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_btncreateActionPerformed(evt);
            }
        });

        JM_lblusername.setBackground(new java.awt.Color(255, 255, 255));
        JM_lblusername.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        JM_lblusername.setForeground(new java.awt.Color(255, 255, 255));
        JM_lblusername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JM_lblusername.setText("User Name");

        JM_usertable.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        JM_usertable.setForeground(new java.awt.Color(102, 0, 102));
        JM_usertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JM_jScrollPane1.setViewportView(JM_usertable);

        JM_lblpwd.setBackground(new java.awt.Color(255, 255, 255));
        JM_lblpwd.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        JM_lblpwd.setForeground(new java.awt.Color(255, 255, 255));
        JM_lblpwd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JM_lblpwd.setText("Password");

        JM_lblemp.setBackground(new java.awt.Color(255, 255, 255));
        JM_lblemp.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        JM_lblemp.setForeground(new java.awt.Color(255, 255, 255));
        JM_lblemp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JM_lblemp.setText("Employee");

        JM_empcb.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        JM_empcb.setForeground(new java.awt.Color(0, 153, 153));
        JM_empcb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        JM_lblorg.setBackground(new java.awt.Color(255, 255, 255));
        JM_lblorg.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        JM_lblorg.setForeground(new java.awt.Color(255, 255, 255));
        JM_lblorg.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JM_lblorg.setText("Organization");

        JM_orgcb.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        JM_orgcb.setForeground(new java.awt.Color(0, 153, 153));
        JM_orgcb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JM_orgcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_orgcbActionPerformed(evt);
            }
        });

        JM_lblrole.setBackground(new java.awt.Color(255, 255, 255));
        JM_lblrole.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        JM_lblrole.setForeground(new java.awt.Color(255, 255, 255));
        JM_lblrole.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JM_lblrole.setText("Role");

        JM_rolecb.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        JM_rolecb.setForeground(new java.awt.Color(0, 153, 153));
        JM_rolecb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JM_rolecb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_rolecbActionPerformed(evt);
            }
        });

        JM_btnback.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        JM_btnback.setForeground(new java.awt.Color(0, 153, 153));
        JM_btnback.setText("<< Back");
        JM_btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_btnbackActionPerformed(evt);
            }
        });

        JM_lbltitle.setBackground(new java.awt.Color(255, 255, 255));
        JM_lbltitle.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        JM_lbltitle.setForeground(new java.awt.Color(255, 255, 255));
        JM_lbltitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JM_lbltitle.setText("MANAGE USER ACCOUNT WORKAREA");

        JM_txtusername.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        JM_txtusername.setForeground(new java.awt.Color(102, 0, 102));

        JM_txtpwd.setForeground(new java.awt.Color(102, 0, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(JM_lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JM_btnback)
                            .addComponent(JM_lblpwd)
                            .addComponent(JM_lblorg)
                            .addComponent(JM_lblemp)
                            .addComponent(JM_lblrole)
                            .addComponent(JM_lblusername))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(JM_btncreate))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JM_orgcb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JM_rolecb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JM_txtusername)
                                    .addComponent(JM_empcb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JM_txtpwd, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(216, 216, 216)
                        .addComponent(JM_jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(327, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JM_lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JM_lblorg)
                            .addComponent(JM_orgcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JM_lblemp)
                            .addComponent(JM_empcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JM_lblrole)
                            .addComponent(JM_rolecb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JM_lblusername)
                            .addComponent(JM_txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JM_lblpwd)
                            .addComponent(JM_txtpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(JM_btncreate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JM_jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, Short.MAX_VALUE)
                .addComponent(JM_btnback)
                .addGap(105, 105, 105))
        );
    }// </editor-fold>//GEN-END:initComponents
 private boolean checkPassword(String input){
        Pattern pattern = Pattern.compile("^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[$#&])[A-Za-z\\d$#*&]{6,}$");
        Matcher matcher = pattern.matcher(input);
        return matcher.matches();
    }
    private void JM_btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_btncreateActionPerformed
        String UName = JM_txtusername.getText();
        String Pwd = String.valueOf(JM_txtpwd.getPassword());
        Organisation org = (Organisation) JM_orgcb.getSelectedItem();

        Role role = (Role) JM_rolecb.getSelectedItem();
        if(JM_empcb.getSelectedItem()==null){
            JOptionPane.showMessageDialog(null, "Select Employee/ Create New Employee");
            return;
        }
        Employee emp = (Employee) JM_empcb.getSelectedItem();
        if(UName.equals("") || UName==null || Pwd.equals("") || Pwd==null){
            JOptionPane.showMessageDialog(null, "Emter Login information.");
            return;
        }

        for(UserAccount acc:org.getUserAccDir().getUserAccList()){
            if(acc.getUname().equals(UName)){
                JOptionPane.showMessageDialog(null, "This username is already in use.");
                return;
            }
        }
        for(UserAccount acc:org.getUserAccDir().getUserAccList()){
            if(acc.getEmp()== emp){
                JOptionPane.showMessageDialog(null, "This employee already exists for other account.");
                return;
            }
        }
        if(org.getName().equals("Volunteer Organization")){
            Volunteer vol = (Volunteer) emp;
            org.getUserAccDir().createAccount(UName, Pwd, vol, role);

        } else {
            org.getUserAccDir().createAccount(UName, Pwd, emp, role);
        }
        JM_txtusername.setText("");
        JM_txtpwd.setText("");
        autoPopData();
    }//GEN-LAST:event_JM_btncreateActionPerformed

    private void JM_orgcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_orgcbActionPerformed
        Organisation organization = (Organisation) JM_orgcb.getSelectedItem();
        if (organization != null){
            populateEmployeeComboBox(organization);
            populateRoleComboBox(organization);
        }
    }//GEN-LAST:event_JM_orgcbActionPerformed

    private void JM_rolecbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_rolecbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JM_rolecbActionPerformed

    private void JM_btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_btnbackActionPerformed

        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_JM_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JM_btnback;
    private javax.swing.JButton JM_btncreate;
    private javax.swing.JComboBox JM_empcb;
    private javax.swing.JScrollPane JM_jScrollPane1;
    private javax.swing.JLabel JM_lblemp;
    private javax.swing.JLabel JM_lblorg;
    private javax.swing.JLabel JM_lblpwd;
    private javax.swing.JLabel JM_lblrole;
    private javax.swing.JLabel JM_lbltitle;
    private javax.swing.JLabel JM_lblusername;
    private javax.swing.JComboBox JM_orgcb;
    private javax.swing.JComboBox JM_rolecb;
    private javax.swing.JPasswordField JM_txtpwd;
    private javax.swing.JTextField JM_txtusername;
    private javax.swing.JTable JM_usertable;
    // End of variables declaration//GEN-END:variables
}
