/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.SystemAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author krishna
 */
public class EnterprisePanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EcoSystem system;
    /**
     * Creates new form EnterprisePanel
     */
    public EnterprisePanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;

        autoPopEnt();
        autoPopComboBox();
    }

    private void autoPopEnt() {
        DefaultTableModel mdl = (DefaultTableModel) tblEnterprise.getModel();

        mdl.setRowCount(0);
        for (Network net : system.getNetList()) {
            for (Enterprise ent : net.getEntDir().getEntList()) {
                Object[] row = new Object[3];
                row[0] = ent;
                row[1] = net.getName();
                row[2] = ent.getEntType().getType();

                mdl.addRow(row);
            }
        }
    }
    
    private void autoPopComboBox() {
        cbEntNetwork.removeAllItems();
        cbEntType.removeAllItems();

        for (Network net : system.getNetList()) {
            cbEntNetwork.addItem(net);
        }
        for (Enterprise.EntType type : Enterprise.EntType.values()) {
            cbEntType.addItem(type);
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbEntNetwork = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtEntName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbEntType = new javax.swing.JComboBox();
        btnEntAdd = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnterprise = new javax.swing.JTable();
        btnEnterpriseDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font(".SF NS Mono", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Network");

        cbEntNetwork.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        cbEntNetwork.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font(".SF NS Mono", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");

        txtEntName.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font(".SF NS Mono", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enterprise Type");

        cbEntType.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        cbEntType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbEntType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEntTypeActionPerformed(evt);
            }
        });

        btnEntAdd.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        btnEntAdd.setForeground(new java.awt.Color(0, 153, 153));
        btnEntAdd.setText("Add");
        btnEntAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntAddActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 153, 153));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MANAGE ENTERPRISE WORKAREA");

        tblEnterprise.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        tblEnterprise.setForeground(new java.awt.Color(102, 0, 102));
        tblEnterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Enterprise Name", "Network", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEnterprise);

        btnEnterpriseDelete.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        btnEnterpriseDelete.setForeground(new java.awt.Color(0, 153, 153));
        btnEnterpriseDelete.setText("DELETE");
        btnEnterpriseDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterpriseDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(255, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbEntNetwork, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbEntType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEntName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(btnEntAdd))))
                    .addComponent(btnEnterpriseDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(255, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnEnterpriseDelete)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbEntNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbEntType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEntName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnEntAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntAddActionPerformed

        Network net = (Network) cbEntNetwork.getSelectedItem();
        Enterprise.EntType type = (Enterprise.EntType) cbEntType.getSelectedItem();

        if (net == null || type == null) {
            JOptionPane.showMessageDialog(null, "Invalid Input.");
            return;
        }

        String name = txtEntName.getText();
        if(name.equals("") || name==null){
            JOptionPane.showMessageDialog(null, "Name field Mandatory.");
            return;
        }
        for(Enterprise ent:net.getEntDir().getEntList()){
            if(ent.getName().equalsIgnoreCase(name)){
                JOptionPane.showMessageDialog(null, "Existing Enterprise.");
                return;
            }
        }

        net.getEntDir().createEnt(name, type);

        autoPopEnt();
        
        txtEntName.setText("");
    }//GEN-LAST:event_btnEntAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnEnterpriseDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterpriseDeleteActionPerformed

        int selectedRow = tblEnterprise.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Make a row selection for enterprise deletion.", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            Enterprise ent = (Enterprise) tblEnterprise.getValueAt(selectedRow, 0);

            for (Network net : system.getNetList()) {
                for (Enterprise enterprise : net.getEntDir().getEntList()) {

                    if (ent == enterprise) {
                        net.getEntDir().getEntList().remove(ent);
                        break;
                    }

                }
            }

            JOptionPane.showMessageDialog(null, "Successful deletion of enterprise.");
            autoPopEnt();
        }
    }//GEN-LAST:event_btnEnterpriseDeleteActionPerformed

    private void cbEntTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEntTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEntTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEntAdd;
    private javax.swing.JButton btnEnterpriseDelete;
    private javax.swing.JComboBox cbEntNetwork;
    private javax.swing.JComboBox cbEntType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEnterprise;
    private javax.swing.JTextField txtEntName;
    // End of variables declaration//GEN-END:variables
}
