/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.HealthRole;

/**
 *
 * @author gauri
 */

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrg;
import Business.Organization.HealthOrg;
import Business.Organization.Organisation;
import Business.Organization.PharmacyOrg;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HospitalDoctorWorkReq;
import Business.WorkQueue.HospitalPharmacyWorkReq;
import Business.WorkQueue.VolunteerStorageWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import UI.DoctorRole.ProcessPanel;


public class PharmacyWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PharmacyWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private HealthOrg org;
    private Enterprise ent;
    private UserAccount ua;
    private Network net;
    
    public PharmacyWorkAreaJPanel(JPanel userProcessContainer, UserAccount acc, Enterprise ent, Network net) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.org = org;
        this.ent = ent;
        this.ua = acc;
        this.net=net;
        populateMedReqTbl();
        System.out.println(ua.getMedicalHistory());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnrefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmedreq = new javax.swing.JTable();
        btnnewreq = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnview = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lbltitle = new javax.swing.JLabel();
        lbldelby = new javax.swing.JLabel();
        txtDeliveredBy = new javax.swing.JTextField();
        lbldelcon = new javax.swing.JLabel();
        txtDeliveryContact = new javax.swing.JTextField();
        lbldeldate = new javax.swing.JLabel();
        txtDeliveryDate = new javax.swing.JTextField();
        lblsentby = new javax.swing.JLabel();
        txtSentby = new javax.swing.JTextField();
        lblsendercon = new javax.swing.JLabel();
        txtSenderContact = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 153, 153));
        setForeground(new java.awt.Color(102, 0, 102));

        btnrefresh.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        btnrefresh.setForeground(new java.awt.Color(0, 153, 153));
        btnrefresh.setText("Refresh");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(0, 153, 153));

        tblmedreq.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        tblmedreq.setForeground(new java.awt.Color(102, 0, 102));
        tblmedreq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Address", "MedicineList", "Pharmacist", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblmedreq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblmedreqMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblmedreq);

        btnnewreq.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        btnnewreq.setForeground(new java.awt.Color(0, 153, 153));
        btnnewreq.setText("New Request");
        btnnewreq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewreqActionPerformed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        btndelete.setForeground(new java.awt.Color(0, 153, 153));
        btndelete.setText("Delete Request");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnview.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        btnview.setForeground(new java.awt.Color(0, 153, 153));
        btnview.setText("View Status or Updates");
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font(".SF NS Mono", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 153, 153));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lbltitle.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        lbltitle.setForeground(new java.awt.Color(255, 255, 255));
        lbltitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle.setText("Request Pharmacy Work Area");

        lbldelby.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        lbldelby.setForeground(new java.awt.Color(255, 255, 255));
        lbldelby.setText("Delivered By");

        txtDeliveredBy.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        txtDeliveredBy.setForeground(new java.awt.Color(102, 0, 102));

        lbldelcon.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        lbldelcon.setForeground(new java.awt.Color(255, 255, 255));
        lbldelcon.setText("Delivery Contact");

        txtDeliveryContact.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        txtDeliveryContact.setForeground(new java.awt.Color(102, 0, 102));

        lbldeldate.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        lbldeldate.setForeground(new java.awt.Color(255, 255, 255));
        lbldeldate.setText("Delivery Date");

        txtDeliveryDate.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        txtDeliveryDate.setForeground(new java.awt.Color(102, 0, 102));

        lblsentby.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        lblsentby.setForeground(new java.awt.Color(255, 255, 255));
        lblsentby.setText("Sent By");

        txtSentby.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        txtSentby.setForeground(new java.awt.Color(102, 0, 102));

        lblsendercon.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        lblsendercon.setForeground(new java.awt.Color(255, 255, 255));
        lblsendercon.setText("Sender Contact");

        txtSenderContact.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        txtSenderContact.setForeground(new java.awt.Color(102, 0, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbldelby)
                    .addComponent(txtDeliveredBy, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldelcon)
                    .addComponent(txtDeliveryContact, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldeldate)
                    .addComponent(txtDeliveryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblsendercon)
                    .addComponent(txtSenderContact, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSentby, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblsentby)))
                .addContainerGap(432, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(75, 75, 75)
                        .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnnewreq)
                            .addGap(148, 148, 148)
                            .addComponent(btnview)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btndelete))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btndelete, btnnewreq, btnview});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbltitle)
                        .addComponent(btnrefresh)))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnewreq, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnview, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldelby)
                    .addComponent(lblsentby))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDeliveredBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSentby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldelcon)
                    .addComponent(lblsendercon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDeliveryContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSenderContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbldeldate)
                .addGap(18, 18, 18)
                .addComponent(txtDeliveryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btndelete, btnnewreq, btnview});

    }// </editor-fold>//GEN-END:initComponents

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed

        populateMedReqTbl();
        txtDeliveredBy.setText("");
        txtDeliveryContact.setText("");
        txtDeliveryDate.setText("");
        txtSenderContact.setText("");
        txtSentby.setText("");
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void tblmedreqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmedreqMouseClicked
        int selectedRow = tblmedreq.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showConfirmDialog(null, "Please select a row from table to view details.!","Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{

            WorkRequest w = (WorkRequest) tblmedreq.getValueAt(selectedRow, 0);
            HospitalPharmacyWorkReq wr = (HospitalPharmacyWorkReq) w;

            txtDeliveredBy.setText(wr.getDelivery().getEmp().getName());
            txtDeliveryContact.setText(wr.getDeliveryNo());
            SimpleDateFormat formatter = new SimpleDateFormat("dd MMM, yyyy");
            Date date = wr.getExpectedDelivery();
            String pickDate = formatter.format(date);
            txtDeliveryDate.setText(pickDate);
            txtSenderContact.setText(wr.getRecieverNo());
            txtSentby.setText(wr.getReceiver().getEmp().getName());

        }
    }//GEN-LAST:event_tblmedreqMouseClicked

    private void btnnewreqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewreqActionPerformed

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("PharmacyReqJPanel", new PharmacyReqJPanel(userProcessContainer, ua, ent, net));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnnewreqActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        int selectedRow = tblmedreq.getSelectedRow();
        if(selectedRow>=0){
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Do you want to Delete this request??","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
                HospitalPharmacyWorkReq request = (HospitalPharmacyWorkReq)tblmedreq.getValueAt(selectedRow, 0);
                if(request.getStatus().equalsIgnoreCase("completed"))
                {
                    JOptionPane.showMessageDialog(null, "Completed Request Cannot be deleted.");
                    return;
                }
                Organisation org = null;
                for(Enterprise ent: net.getEntDir().getEntList())
                {
                    if(ent.getEntType().equals(ent.getEntType().Hospital))
                    {
                        for (Organisation organization : ent.getOrgDir().getOrgList())
                        {
                            if (organization instanceof PharmacyOrg){
                                org = organization;
                                org.getWorkQueue().getWrList().remove(request);

                                for(UserAccount a : org.getUserAccDir().getUserAccList())
                                {
                                    for(WorkRequest w: a.getWorkQueue().getWrList())
                                    {
                                        if(w.equals(request))
                                        {
                                            a.getWorkQueue().getWrList().remove(request);
                                            break;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }

                if (org!=null){
                    ua.getWorkQueue().getWrList().remove(request);
                }
                populateMedReqTbl();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblmedreq.getSelectedRow();
        if(selectedRow>=0)
        {
            HospitalPharmacyWorkReq req = (HospitalPharmacyWorkReq)tblmedreq.getValueAt(selectedRow, 0);
            if(req.getStatus().equalsIgnoreCase("Sent"))
            {
                JOptionPane.showMessageDialog(null, "Updates unavailable");
                return;
            }
            ViewStatusInfoJPanel viewStatusInfoJPanel = new ViewStatusInfoJPanel(userProcessContainer,ent,ua,req);
            userProcessContainer.add("ViewStatusJPanel", viewStatusInfoJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Select a Row");
        }

    }//GEN-LAST:event_btnviewActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnnewreq;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnview;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbldelby;
    private javax.swing.JLabel lbldelcon;
    private javax.swing.JLabel lbldeldate;
    private javax.swing.JLabel lblsendercon;
    private javax.swing.JLabel lblsentby;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JTable tblmedreq;
    private javax.swing.JTextField txtDeliveredBy;
    private javax.swing.JTextField txtDeliveryContact;
    private javax.swing.JTextField txtDeliveryDate;
    private javax.swing.JTextField txtSenderContact;
    private javax.swing.JTextField txtSentby;
    // End of variables declaration//GEN-END:variables
public void populateMedReqTbl() {
       DefaultTableModel mdl = (DefaultTableModel) tblmedreq.getModel();
       mdl.setRowCount(0);
       for (Iterator<WorkRequest> it = ua.getWorkQueue().getWrList().iterator(); it.hasNext();) 
       {
           WorkRequest wrReq = it.next();
           if(wrReq instanceof HospitalPharmacyWorkReq){
           HospitalPharmacyWorkReq req = (HospitalPharmacyWorkReq) wrReq;
           Object[] row = new Object[5];
           row[0] = req;
           row[1]=req.getAddress();
           row[2]=req.getMedList();
           row[3] = req.getReceiver();
           row[4] = req.getStatus();
           mdl.addRow(row);
           }
           
       }
}

}
