/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.HealthRole;

/**
 *
 * @author Mrinalini
 */
import UI.PharmacistRole.*;
import Business.Enterprise.Enterprise;
import Business.Medicare;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HospitalDoctorWorkReq;
import Business.WorkQueue.HospitalPharmacyWorkReq;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import UI.HealthRole.MedJPanel;


public class ViewStatusInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewStatusInfoJPanel
     */
     private JPanel userProcessContainer;
    private Enterprise enterprise;
    private HospitalPharmacyWorkReq request;
    private UserAccount userAccount;
    public ViewStatusInfoJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount account, HospitalPharmacyWorkReq request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.request = request;
        populatetblmed();
        txtadd.setText(request.getAddress());
        txtmsg.setText(request.getMessage());
        btnsubmit.setVisible(false);
        btnuploadpres.setVisible(false);
        
        if(request.getStatus().equals("Declined")){
            btnuploadpres.setVisible(true);
            btnsubmit.setVisible(true);
        }
        
        if(request.getPrescription()==null){
            lblimg.setText("No Image Uploaded");
            lblimg.setHorizontalAlignment(SwingConstants.CENTER);
        }
        else{
            lblimg.setText("");
            lblimg.setIcon(Imgresize(request.getPrescription()));
        }
    }
    private ImageIcon Imgresize(String ImagePath){
        ImageIcon img = new ImageIcon(ImagePath);
        Image img1 = img.getImage();
        Image newImage = img1.getScaledInstance(272,306, Image.SCALE_SMOOTH);
        ImageIcon image2 = new ImageIcon(newImage);
        return image2;
        
      }
        private void populatetblmed() {
       List<Medicare> medlist = request.getMedList();
        DefaultTableModel mdl = (DefaultTableModel) tblmed.getModel();
        mdl.setRowCount(0);
        for(Medicare med:medlist){
            Object[] row =new Object[2];
            row[0] = med;
            row[1] = med.getMed_quantity();
            mdl.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnback = new javax.swing.JButton();
        lbladd = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtmsg = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblmed = new javax.swing.JTable();
        lblprescription = new javax.swing.JLabel();
        lblmsg = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtadd = new javax.swing.JTextArea();
        lblimg = new javax.swing.JLabel();
        btnuploadpres = new javax.swing.JButton();
        btnsubmit = new javax.swing.JButton();
        lbltitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        btnback.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        btnback.setForeground(new java.awt.Color(0, 153, 153));
        btnback.setText("<< Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        lbladd.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        lbladd.setForeground(new java.awt.Color(255, 255, 255));
        lbladd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbladd.setText("Address:");

        txtmsg.setEditable(false);
        txtmsg.setBackground(new java.awt.Color(204, 204, 204));
        txtmsg.setColumns(20);
        txtmsg.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        txtmsg.setForeground(new java.awt.Color(102, 0, 102));
        txtmsg.setRows(5);
        jScrollPane1.setViewportView(txtmsg);

        tblmed.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        tblmed.setForeground(new java.awt.Color(102, 0, 102));
        tblmed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblmed);

        lblprescription.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        lblprescription.setForeground(new java.awt.Color(255, 255, 255));
        lblprescription.setText("Prescription:");

        lblmsg.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        lblmsg.setForeground(new java.awt.Color(255, 255, 255));
        lblmsg.setText("Message:");

        txtadd.setEditable(false);
        txtadd.setBackground(new java.awt.Color(204, 204, 204));
        txtadd.setColumns(20);
        txtadd.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        txtadd.setForeground(new java.awt.Color(102, 0, 102));
        txtadd.setRows(5);
        jScrollPane3.setViewportView(txtadd);

        lblimg.setBackground(new java.awt.Color(204, 204, 204));
        lblimg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnuploadpres.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        btnuploadpres.setForeground(new java.awt.Color(0, 153, 153));
        btnuploadpres.setText("Upload Prescription");
        btnuploadpres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuploadpresActionPerformed(evt);
            }
        });

        btnsubmit.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        btnsubmit.setForeground(new java.awt.Color(0, 153, 153));
        btnsubmit.setText("SUBMIT");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        lbltitle.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        lbltitle.setForeground(new java.awt.Color(255, 255, 255));
        lbltitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle.setText("View Request Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbltitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnback)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbladd)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblprescription)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnuploadpres))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(lblmsg)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblimg, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnback)
                .addGap(15, 15, 15)
                .addComponent(lbltitle)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblprescription)
                    .addComponent(btnuploadpres))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblimg, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbladd)
                    .addComponent(lblmsg)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(28, 28, 28)
                .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PharmacyWorkAreaJPanel panel = (PharmacyWorkAreaJPanel) component;
        panel.populateMedReqTbl();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnbackActionPerformed

    private void btnuploadpresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuploadpresActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        //filter the files
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int res = file.showSaveDialog(null);
        //if the user click on save in Jfilechooser
        if(res == JFileChooser.APPROVE_OPTION){
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            request.setPrescription(path);
            lblimg.setText("");
            lblimg.setIcon(Imgresize(path));
        }
        //if the user click on save in Jfilechooser

        else if(res == JFileChooser.CANCEL_OPTION){
            System.out.println("No File Select");
        }
    }//GEN-LAST:event_btnuploadpresActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
        if(request.getPrescription()==null || request.getPrescription().equals("")){
            JOptionPane.showConfirmDialog(null, "Upload Prescription");
            return;
        }
        JOptionPane.showMessageDialog(null, "Submitted");
        request.setStatus("Updated");

    }//GEN-LAST:event_btnsubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JButton btnuploadpres;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbladd;
    private javax.swing.JLabel lblimg;
    private javax.swing.JLabel lblmsg;
    private javax.swing.JLabel lblprescription;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JTable tblmed;
    private javax.swing.JTextArea txtadd;
    private javax.swing.JTextArea txtmsg;
    // End of variables declaration//GEN-END:variables
}
